baseURL = 'https://ghesedoon.ir/'
theme = 'PaperMod'
defaultContentLanguage = 'fa'
defaultContentLanguageInSubdir = false

[params]
  defaultTheme = "auto"
  defaultAppearance = "light"
  customCSS = ["css/custom.css"]
  displayFullLangName = true
  mainSections = ["posts"]

[languages]
  [languages.fa]
    languageName = "فارسی"
    languageCode = "fa-ir"
    languageDirection = "rtl"
    title = "قصه دون"
    weight = 1

    [languages.fa.params]
      rtl = true
      description = "قصه‌های کودکانه قصه دون"

    [[languages.fa.menu.main]]
      identifier = "tags"
      name = "برچسب‌ها"
      url = "/tags/"
      weight = 10

    [[languages.fa.menu.main]]
      identifier = "donate"
      name = "حمایت مالی"
      url = "/donate/"
      weight = 20

  [languages.en]
    languageName = "English"
    languageCode = "en"
    languageDirection = "ltr"
    title = "Ghesedoon"
    weight = 2

    [languages.en.params]
      rtl = false
      description = "Children's stories from Ghesedoon"

    [[languages.en.menu.main]]
      identifier = "tags"
      name = "Tags"
      url = "/tags/"
      weight = 10

    [[languages.en.menu.main]]
      identifier = "donate"
      name = "Donate"
      url = "/donate/"
      weight = 20
