baseURL = 'https://ghesedoon.ir/'
theme = 'PaperMod'
defaultContentLanguage = 'fa'
defaultContentLanguageInSubdir = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  includeNewer = true
  threshold = 60
  toLower = true

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "title"
    weight = 10

[params]
  env = "production"
  defaultTheme = "auto"
  defaultAppearance = "light"
  displayFullLangName = true
  mainSections = ["posts"]
  images = ["/og-image.png"]
  paymentUrl = "https://pay.noxte.ir/link/780257"

  [params.label]
    icon = "/logo.png"
    iconHeight = 32

  [params.cover]
    hiddenInSingle = true

  [params.fuseOpts]
    keys = ["title", "summary"]
    threshold = 0.3
    ignorelocation = true
    minmatchcharlength = 2

[languages]
  [languages.fa]
    label = "فارسی"
    locale = "fa-IR"
    direction = "rtl"
    title = "قصه دون"
    weight = 1

    [languages.fa.params]
      rtl = true
      description = "مجموعه قصه‌ها و داستان‌های آموزنده و جذاب کودکانه برای کودکان فارسی‌زبان همراه با تصاویر زیبا، داستان شب و لالایی برای رشد و سرگرمی فرزند شما در قصه دون."

    [[languages.fa.menu.main]]
      identifier = "search"
      name = "جستجو"
      url = "/search/"
      weight = 5

    [[languages.fa.menu.main]]
      identifier = "tags"
      name = "برچسب‌ها"
      url = "/tags/"
      weight = 10

    [[languages.fa.menu.main]]
      identifier = "premium"
      name = "خرید نسخه انگلیسی 🇬🇧"
      url = "https://pay.noxte.ir/link/780257"
      weight = 15

    [[languages.fa.menu.main]]
      identifier = "donate"
      name = "حمایت مالی"
      url = "/donate/"
      weight = 20

  [languages.en]
    label = "English"
    locale = "en"
    direction = "ltr"
    title = "Ghesedoon"
    weight = 2

    [languages.en.params]
      rtl = false
      description = "Discover delightful illustrated stories, bedtime tales, and educational adventures for children of all ages. Explore a magical world of stories at Ghesedoon."

    [[languages.en.menu.main]]
      identifier = "search"
      name = "Search"
      url = "/search/"
      weight = 5

    [[languages.en.menu.main]]
      identifier = "tags"
      name = "Tags"
      url = "/tags/"
      weight = 10

    [[languages.en.menu.main]]
      identifier = "premium"
      name = "Get Access 💳"
      url = "https://pay.noxte.ir/link/780257"
      weight = 15

    [[languages.en.menu.main]]
      identifier = "donate"
      name = "Donate"
      url = "/donate/"
      weight = 20
